# Generated by Django 5.2.11 on 2026-02-28 08:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique session identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the conversation started')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last message timestamp')),
                ('user_metadata', models.JSONField(blank=True, default=dict, help_text='Browser info, location, etc. (JSON)')),
                ('message_count', models.IntegerField(default=0, help_text='Total number of messages in this conversation')),
                ('language', models.CharField(choices=[('en', 'English'), ('ko', 'Korean')], default='en', help_text='Conversation language', max_length=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', help_text='Current conversation status', max_length=20)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='conversatio_created_d82801_idx'), models.Index(fields=['status'], name='conversatio_status_742c74_idx'), models.Index(fields=['language'], name='conversatio_languag_0873d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique message identifier', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant'), ('system', 'System')], help_text='Who sent the message', max_length=20)),
                ('content', models.TextField(help_text='Message text content')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the message was sent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data (tokens, response time, tool usage)')),
                ('session', models.ForeignKey(db_column='session_id', help_text='Which conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique feedback identifier', primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField(choices=[(1, 'Thumbs Up'), (-1, 'Thumbs Down')], help_text='1 = thumbs up, -1 = thumbs down')),
                ('comment', models.TextField(blank=True, help_text='Optional text feedback from user', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When feedback was submitted')),
                ('session', models.ForeignKey(db_column='session_id', help_text='Which conversation this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chatbot.conversation')),
                ('message', models.ForeignKey(blank=True, db_column='message_id', help_text='Specific message being rated (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chatbot.message')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'db_table': 'feedback',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'timestamp'], name='messages_session_f940d1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-timestamp'], name='messages_timesta_865eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role'], name='messages_role_8be1df_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['session', '-timestamp'], name='feedback_session_c9386c_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['rating'], name='feedback_rating_ed839f_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-timestamp'], name='feedback_timesta_17d8d6_idx'),
        ),
    ]
